---
- name: Make sure we go back to default project
  shell: "oc project default"

- name: Check if Fuse 7.0 image streams are available
  shell: "oc describe is jboss-fuse70-java-openshift -n openshift"
  register: imagestream_exists
  when: configure_only == 'false'
  ignore_errors: true

- name: Create image streams for Fuse 7.0
  shell: "oc create -f https://raw.githubusercontent.com/hguerrero/3scale-api-workshop/master/support/templates/fuse-image-streams.json -n openshift"
  when: configure_only == 'false' and imagestream_exists.failed

- name: Check if Fuse 7.0 template is available
  shell: "oc describe template s2i-fuse70-spring-boot-camel -n openshift"
  register: template_exists
  when: configure_only == 'false'
  ignore_errors: true

- name: Create template for Fuse 7.0
  shell: "oc create -f https://raw.githubusercontent.com/hguerrero/3scale-api-workshop/master/support/templates/spring-boot-camel-template.json -n openshift"
  when: configure_only == 'false' and template_exists.failed

- name: Create Backend Database
  shell: "oc new-app -f https://raw.githubusercontent.com/openshift/origin/master/examples/db-templates/mysql-ephemeral-template.json \
  -p MYSQL_PASSWORD=password -p MYSQL_ROOT_PASSWORD=password -p MYSQL_USER=dbuser -n {{ backend_project }}"
  when: configure_only == 'false'
  
- name: Update Deployment Config Backend Database
  shell: "oc set env dc/mysql MYSQL_MAX_CONNECTIONS=512 -n {{ backend_project }}"
  when: configure_only == 'false'
  
- name: Create Backend API service
  shell: "oc new-app s2i-fuse70-spring-boot-camel -p GIT_REPO=https://github.com/hguerrero/3scale-api-workshop \
  -p CONTEXT_DIR=/projects/location-service -p APP_NAME=location-service -p GIT_REF=master -n {{ backend_project }}"
  when: configure_only == 'false'